const ACTIONS = {
	GET_USER: "GET_USER",
	GET_USER_BY_TOKEN: "GET_USER_BY_TOKEN",
	SET_LISTS: "SET_LISTS",
	SET_LIST: "SET_LIST",
	SET_CURRENT_LIST_ID: "SET_CURRENT_LIST_ID",
	SET_CURRENT_LIST_EDITORS_LITE_OBJ: "SET_CURRENT_LIST_EDITORS_LITE_OBJ",
	DELETE_LIST_BY_ID: "DELETE_LIST_BY_ID",
};

export default ACTIONS;
